### ISSUE TITLE
WSDL Process

### ISSUE THREAD

**Issue by f1ana** [matteofabbri/Workday.WebServices#1]
Hello!

I'm currently working on integrating Workday into an application and I am having a bit of trouble importing the WSDL into Visual Studio, or even converting using `svcutil` or `dotnet-svcutil`.  I came across your library and I'm very fascinated at how you were able to take the WSDL into something usable and more so, how you got it working in a .NET Standard project.
If you have a moment, can you tell me how you got this working?  I'm looking to target API version 32.2, so it would seem that I have to figure this out.  If you'd like, I can also prepare a PR to get this library up to date with 32.2!

Thanks,
Chris

**Comment by matteofabbri** [comment]
Hi, sorry the very late response.
Honestly i dont know how to help you, I did this more than one year ago, screaming and punching the screen for more than a month.
Than I found someone that manually fixed the wsdl for an another project.
If I remember right the main problem is changing many dimensions array [][] to single dimention array.
And the fact that are millions of them.
