### ISSUE TITLE
Processing error occurred. The task submitted is not authorized.

### ISSUE THREAD

**Issue by hpatel16051986** [matteofabbri/Workday.WebServices#3]
I am getting below error while sending the request.
"Processing error occurred. The task submitted is not authorized."

can anybody know about this.

Thank you 
Hardik

**Comment by aaroncalderon** [comment]
This is a permissions issue.
The user that you are using to submit the request does not have the proper domain permissions.

Find out the proper permissions required (which domains) for the request you are trying to make.
Make sure the user has those permissions.

Regards
